### ISSUE TITLE
Use function types and lambda expressions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by HyeonJungHam** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#113]
**URL of codelab**

[https://developer.android.com/codelabs/basic-android-kotlin-compose-function-types-and-lambda?authuser=2&hl=ko&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%3Fauthuser%3D2%26hl%3Dko%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-function-types-and-lambda#3 ](url)

**In which task and step of the codelab can this issue be found?**

using lambda expressions in Kotlin, step 4

**Describe the problem**

Kotlin Playground Error

![스크린샷 2023-12-20 102854](https://github.com/google-developer-training/basic-android-kotlin-compose-training-dice-roller/assets/40817279/ebe96b5a-0823-479e-b516-a3306428ea7e)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

Tried on 2023.12.20

**Comment by johnshea** [comment]
Hi @HyeonJungHam 

Thank you for writing in.

The error is because your code is missing the null check in the `else` clause.

Your code is missing this...
```
        if (extraTreat != null) {
            println(extraTreat(5))
        }
```

Once you correct this omission, you should be good.

Hope you are enjoying the course!

Regards.

<img width="857" alt="Screenshot 2024-03-15 at 12 23 02 PM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-dice-roller/assets/7107817/9e40d1d5-2326-49f2-9061-0408add1cd05">
