### ISSUE TITLE
Use function types and lambda expressions in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by PeterS-ZH** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#57]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-compose-function-types-and-lambda?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-function-types-and-lambda#5

**In which task and step of the codelab can this issue be found?**
Task 6. Use the repeat() function
Steps 2 and 3

**Describe the problem**
Not clear why the (4 times) repeated call of 'treatFunction' only prints '5 quarters' **once**
Obviously it does, but if you repeatedly call the same function, repeatedly the same output would seem reasonable. And if this is not the case, it would be nice to have a little explanation there.
Tnx!

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
Irrelevant - output is shown in the codelab and the Kotlin Playground also produces the same results.

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/127112741/224675463-8bd9d1aa-804f-4750-afe5-9349d5fb81b5.png)

**Comment by johnshea** [comment]
Hi @PeterS-ZH 

Thanks for reaching out to us and sharing your feedback with us.

To address your issue...

The way the code is written `5 quarters` is only printing once because it gets printed during the variable assignment `val treatFunction = trickOrTreat(false) { "$it quarters" }`. It is not being printed when the function `treatFunction()` is called.

This is causing the confusion and will be passed to the appropriate team for further consideration.

I hope you are enjoying the course.

Regards.
