### ISSUE TITLE
Write conditionals in Kotlin: Android Basics with Compose

### ISSUE THREAD

**Issue by KiselDaniel** [google-developer-training/basic-android-kotlin-compose-training-dice-roller#66]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-conditionals?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-conditionals#2

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
8. point running a program with input "Slow" shouldn't print "Slow", there is mistake the input should be string "Yellow" :-)

**Comment by johnshea** [comment]
Hi @KiselDaniel 

Thank you for writing in with this issue.

I reviewed the lesson and cannot find this mistake. Perhaps it has already been addressed.

If you are able, please see if the issue still exists.

If it does, please open a new issue and attach a screenshot so that we can find it and correct it.

Hope you are enjoying the course!

Regards.
